package info.kwarc.sissi.sally.interaction.document.spreadsheet;

public class CellInformation {
	private String pos, value, formula;
	private CellSpaceInformation cellCoordinates, cellSize;
	
	CellInformation(String pos, String value, String formula, int rowSize, int columnSize) {
		this.pos = pos;
		this.value = value;
		this.formula = formula;
		cellSize = new CellSpaceInformation(rowSize, columnSize);
		cellCoordinates = Util.convertCellPosition(pos);
	}
	
	// Generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((cellCoordinates == null) ? 0 : cellCoordinates.hashCode());
		result = prime * result
				+ ((cellSize == null) ? 0 : cellSize.hashCode());
		result = prime * result + ((formula == null) ? 0 : formula.hashCode());
		result = prime * result + ((pos == null) ? 0 : pos.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	// Generated by Eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CellInformation other = (CellInformation) obj;
		if (cellCoordinates == null) {
			if (other.cellCoordinates != null)
				return false;
		} else if (!cellCoordinates.equals(other.cellCoordinates))
			return false;
		if (cellSize == null) {
			if (other.cellSize != null)
				return false;
		} else if (!cellSize.equals(other.cellSize))
			return false;
		if (formula == null) {
			if (other.formula != null)
				return false;
		} else if (!formula.equals(other.formula))
			return false;
		if (pos == null) {
			if (other.pos != null)
				return false;
		} else if (!pos.equals(other.pos))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}


	public String getPos() {
		return pos;
	}
	
	public String getValue() {
		return value;
	}
	
	public String getFormula() {
		return formula;
	}
	
	public int getRowSize() {
		return cellSize.getRow();
	}
	
	public int getColumnSize() {
		return cellSize.getColumn();
	}
	
	public CellSpaceInformation getSize() {
		return cellSize;
	}
	
	public CellSpaceInformation getCellCoordinates() {
		return cellCoordinates;
	}
}
