package info.kwarc.sissi.sally.interaction.document.spreadsheet;

public class CellSpaceInformation {
	private int row, column;
	
	CellSpaceInformation(int row, int column) {
		this.row = row;
		this.column = column;
	}
	
	// Generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + column;
		result = prime * result + row;
		return result;
	}

	// Generated by Eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CellSpaceInformation other = (CellSpaceInformation) obj;
		if (column != other.column)
			return false;
		if (row != other.row)
			return false;
		return true;
	}

	public int getRow() {
		return row;
	}

	public int getColumn() {
		return column;
	}
	
	public CellSpaceInformation add(CellSpaceInformation c) {
		return new CellSpaceInformation(this.getRow() + c.getRow(), this.getColumn() + c.getColumn());
	}
}
